### ISSUE TITLE
Seek bar is 20 seconds off from mouse location

### ISSUE THREAD

**Issue by dstrivelli** [paypal/accessible-html5-video-player#106] opened 2017-11-07 15:39 UTC
When I'm trying to use the seek bar, the progress is being applied 20s (approximately an inch to the right) of where I'm clicking.

Upon inspection, it looks like this.offsetLeft is always producing 0, not the offset from the side of the screen.

![screen shot 2017-11-07 at 10 32 56 am](https://user-images.githubusercontent.com/31289764/32502091-d7b7f896-c3a7-11e7-8227-b36e9f84e4aa.png)

**Comment by dstrivelli** [comment] 2017-11-07 16:34
Switching:
		`obj.pos = (e.pageX - this.offsetLeft) / this.offsetWidth;`
To:
                `obj.pos = (e.pageX - $(this).offset().left) / this.offsetWidth;`
Introduces jQuery as a dependency, but it does function as expected using "their" offset instead.

**Comment by hozefaj** [comment] 2017-11-07 16:49
We cannot have jQuery as a dependency. The idea is to have the code is vanilla JavaScript so it be dropped without extra stuff

**Comment by dstrivelli** [comment] 2017-11-07 16:50
Makes sense. I'm not really suggesting that this codebase take on JQ as a dependency, but moreso pointing out that whatever IT is doing differently would provide the proper functionality in these situations.

**Comment by hozefaj** [comment] 2017-11-10 17:11
@dstrivelli What browser & version are you seeing the error?

**Comment by nomo-kazza** [comment] 2018-06-30 21:48
Hi @dstrivelli, 

I am facing the same problem. The tooltip and the seek bar not properly displayed in the correct position. To reproduce the issue please add position relative CSS property in wrapper div. If any of the parent element of px-video-container div set to position relative, this issue will appear. 
![screen recording 2018-06-30 at 05 36 pm](https://user-images.githubusercontent.com/5960127/42129247-7fd9c042-7c8d-11e8-999f-feeff82b1633.gif)

I think the following change will fix the issue
<img width="807" alt="screen shot 2018-06-30 at 5 32 48 pm" src="https://user-images.githubusercontent.com/5960127/42129249-a376605a-7c8d-11e8-8014-0bd632e17e55.png">

Thanks

**Comment by hozefaj** [comment] 2018-07-01 04:37
@nomo-kazza If you are willing to send a PR with the required updates, happy to review and help you get it merged 👍

**Comment by nomo-kazza** [comment] 2018-07-02 15:09
I will create the PR. can you also update the npm package? (https://www.npmjs.com/package/accessible-html5-video-player) since we are using it.

**Closed** 2018-07-04 02:16 UTC
