### ISSUE TITLE
Bug: disabled CC shown again when exiting full screen mode

### ISSUE THREAD

**Issue by medonja** [paypal/accessible-html5-video-player#109] opened 2018-03-12 13:02 UTC
When CC are disabled by the user, and the user enters full screen mode, and exits it again, the CCs are shown again, even the CC button is clearly in the disabled state. Can this be fixed? :)

**Comment by hozefaj** [comment] 2018-03-14 00:28
Not super actively maintaining this right now. But happy to accept a PR for it, if you are up for the task.

**Comment by medonja** [comment] 2018-03-20 07:33
Sorry for not having replied earlier. I will try to fix and make a PR.

**Comment by hozefaj** [comment] 2018-07-04 02:18
@medonja FYI, I am not able to reproduce this issue on my system. Can you tell me browser, OS where you are seeing the issue.

**Comment by weboverhauls** [comment] 2018-07-04 15:09
I cannot repro either (on 4 Mac browsers).

**Comment by nomo-kazza** [comment] 2018-07-04 15:55
@hozefaj, I fixed this issue with my last commit when I fixed seek bar display.

**Comment by hozefaj** [comment] 2018-07-04 16:06
Great. Closing as #110 fixes the issue.

**Closed by hozefaj** 2018-07-04 16:06 UTC
