### ISSUE TITLE
Seeking unreliable if users wish to position video-player-controls elsewhere

### ISSUE THREAD

**Issue by augbog** [paypal/accessible-html5-video-player#32] opened 2015-01-09 01:11 UTC
As of right now the way the progress bar has been implemented is if a user wishes to seek, the library will determine where the user wishes to seek based on where the user has clicked relative to the page.

	// Skip when clicking progress bar
	obj.progressBar.addEventListener('click', function(e) {
		obj.pos = (e.pageX - this.offsetLeft)/ this.offsetWidth;
		obj.movie.currentTime = obj.pos * obj.movie.duration;
		
		// Special handling for "manual" captions
		if (!obj.isTextTracks) {
			adjustManualCaptions(obj);
		}
	});

If a user wants to move the video-player to a different location on the screen, I have found issues with seeking.

To be honest, I actually feel a slider (`input[type="range"]`) might be more appropriate for showing the progress of the video? 

Pros:
* you can change the value similar to how you change the `<progress>` element to show progress while the video is playing
* you can easily retrieve the value the user seeks to.

Cons:
* trouble adding color before slider thumb -- might have to use JS? currently solution I have only works in webkit and not Firefox
* it seems that `input[type="range"]` doesn't interpret floats so the progress of the video looks jumpy

Was hoping to get thoughts on this? I might submit a pull request when I have more done. I started a branch on my repository [here](https://github.com/augbog/accessible-html5-video-player/tree/augbog-slider) and got some partial functionality going.

**Comment by augbog** [comment] 2015-01-12 18:17
Updating: I found that you can fix the problem with moving the video player which is in a container by changing `this.offsetLeft` to  `this.getBoundingClientRect().left`. This makes the video player look at the viewport size rather than the container's offset. We can also add a style so that the video-player has `cursor: pointer` on hover so that its more obvious users can seek with the progress bar.

I also played more with the slider and found that the slider cannot parse float values so it leads to back the problem that was solved in PR #31. For now I won't make a pull for that.

**Comment by farhd** [comment] 2015-02-09 12:04
what about trying instead of:
obj.pos = (e.pageX - this.offsetLeft)/ this.offsetWidth;

this:
obj.pos = e.offsetX / this.offsetWidth;

**Comment by weboverhauls** [comment] 2015-03-01 02:46
What's the issue we're trying to solve here? I'm not experiencing any problems with the current progress indicator (which I feel is semantically correct). Can't reproduce "If a user wants to move the video-player to a different location on the screen".

**Comment by augbog** [comment] 2015-03-01 20:18
The issue I was having is if I wanted to move the video player control bar, the seeking wouldn't work correctly. 

![paypal-video-player](https://cloud.githubusercontent.com/assets/2054339/6432633/c296c948-c00c-11e4-88bc-eb7fdb9c10ad.png)

I changed the issue title to use a slider instead because I saw a lot of other video players doing this but I don't think that's actually necessary. I'll change it back to what it originally was. Maybe I'm just moving the video player controls in an improper way? I can close this if this isn't actually an issue.

**Comment by weboverhauls** [comment] 2015-03-02 02:56
In any case, I believe this is a customization issue. Did you try the suggestion above by @farhd? I'm going to close the issue, but if you find a fix which also works well in Master, then please feel free to make a PR. Thanks for your help, @augbog!

**Closed by weboverhauls** 2015-03-02 02:56 UTC

**Comment by augbog** [comment] 2015-03-03 18:42
Thanks :) I'll play around with it!
